#!/bin/bash
# for deinterleaving OSGB AddressBasePremium dataset files

# $1: gz or zip
mode=${1:-zip}

if [ "$mode" = "zip" ]; then
  mkdir -p ../unpacked
  for f in *.zip; do
    echo "unpack $f"
    unzip $f -d ../unpacked/
  done
  cd ../unpacked
fi

mkdir -p ../types

for t in 11 15 21 23 24 28 29 30 31 32; do
  echo $t
  rm -f ../types/t$t.csv ../types/t$t.csv.gz
  case $mode in
    gz)
      zcat *.gz | nice grep "^$t," > ../types/t$t.csv ;;
    zip)
      cat *.csv | nice grep "^$t," > ../types/t$t.csv ;;
  esac
  wc -l ../types/t$t.csv
  nice gzip ../types/t$t.csv
done

if [ "$mode" = "zip" ]; then
  cd ..
  rm -r unpacked
fi
