@startuml

title <b>Simplified AddressBasePremium</b>\nCSV Schema

note "circles indicates primary identifiers\ntriangle: indicates reference identifier\nsquare: indicates technical field\nquestion mark: optional value" as N2

class date_fields << (D,orchid) >> {
 start_date
 end_date?
 last_update_date
 entry_date
}

class Application_cross_reference {
 -record_identifier: 23
}

class Successor {
 -record_identifier: 30
}

class Classification {
 - 1: record_identifier: 32
 - 2: change_type
 - 3: processing_order
 + 4: UPRN
 5; class_key
 6: classification_code
 7: class_scheme
 8: scheme_version
 date_fields
}

class Organisation {
 - 1: record_identifier: 31
 - 2: change_type
 - 3: processing_order
 + 4: UPRN
 5: org_key
 6: organisation
 7: legal_name
 date_fields
}

class Metadata {
 -record_identifier: 29
}

class Header {
 -record_identifier: 10
}

class Trailer {
 -record_identifier: 99
}

class Street << (S,yellow) >> {
 - 1: record_identifier: 11
 - 2: change_type
 - 3:  processing_order
 + 4: USRN
 5: record_type_code
 6: swa_org_ref_naming_code
 7: state_code?
 8: state_date?
 9: street_surface_code?
 10: street_classification?
 11: version: int
 date_fields
 start_xy: bng
 latitude_longitude_ etrs89
 end_xy: bng
 24: tolerance: metres
}

class Street_descriptor << (S,yellow) >> {
 - 1: record_identifier: 15
 - 2: change_type
 - 3: processing_order
 ~ 4: USRN
 5: description
 6: locality?
 7: town_name?
 8: administrative_area
 9: language_code
 date_fields
}

class BLPU << (B,#88FF88) >> {
 - 1: record_identifier: 21
 - 2: change_type
 - 3: processing_order
 + 4: UPRN
 5: logical_status_code
 6: state_code?
 7: state_date?
 ~ 8: parent_uprn?
 coordinate_xy: bng
 latitude_longitude: etrs89
 13: representative_point_code
 ~ 14: local_custodian_code: int
 15: country: char
 date_fields
 20: addressbase_postal_code
 21: postcode_locator: char
 22: number_of_child_records: int
}

note left: Basic land and property unit

class Land_and_property_identifier {
 - 1: record_identifier: 24
 - 2: change_type
 - 3: processing_order
 + 4: UPRN
 + 5: LPI_key
 6: language_code
 date_fields
 12: sao_start_number?
 13: sao_start_suffix?
 14: sao_end_number?
 15: sao_end_suffix?
 16: sao_text?
 17: pao_start_number?
 18: pao_start_suffix?
 19: pao_end_number?
 20: pao_end_suffix?
 21: pao_text?
 22: usrn
 23: usrn_match_indicator_code
 24: area_name?
 25: vertical_level?
 26: official_flag_code?
}

class Delivery_point_address {
 - 1: record_identifier: 28
 - 2: change_type
 - 3: processing_order
 + 4: UPRN
 + 5: UDPRN
 6: organisation_name?
 7: department_name?
 8: sub_building_name?
 9: building_name?
 10: building_number?
 11: dependent_thoroughfare?
 12: thoroughfare?
 13: double_dependent_locality?
 14: dependent_locality?
 15: post_town
 16: postcode
 17: postcode_type_code
 18: delivery_point_suffix_code
 19: welsh_dependent_thoroughfare?
 20: welsh_thoroughfare?
 21: welsh_double_dependent_locality?
 22: welsh_dependent_locality?
 23: welsh_post_town?
 24: po_box_number?
 date_fields
}

BLPU "1" -- "0..1" Delivery_point_address
BLPU "1" -- "1..*" Land_and_property_identifier
Street "1" -- "1..*" Land_and_property_identifier
Street "1" -- "1..*" Street_descriptor
BLPU "1" -- "1..*" Classification
BLPU "1" -- "0..*" Application_cross_reference
BLPU "1" -- "0..*" Successor
BLPU "1" -- "0..*" Organisation

hide class methods
@enduml
